// <auto-generated />
using System;
using FootballScout.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FootballScout.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230331080857_fieldStats")]
    partial class fieldStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("FootballScout.Data.Entities.FieldStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("Aerial")
                        .HasColumnType("integer");

                    b.Property<int>("Attacking")
                        .HasColumnType("integer");

                    b.Property<int>("Defending")
                        .HasColumnType("integer");

                    b.Property<int>("MentalId")
                        .HasColumnType("integer");

                    b.Property<int>("Mentals")
                        .HasColumnType("integer");

                    b.Property<int>("Overall")
                        .HasColumnType("integer");

                    b.Property<int>("PhysicalId")
                        .HasColumnType("integer");

                    b.Property<int>("Physicals")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<int>("TechnicalId")
                        .HasColumnType("integer");

                    b.Property<int>("Technicals")
                        .HasColumnType("integer");

                    b.Property<int>("Vision")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MentalId")
                        .IsUnique();

                    b.HasIndex("PhysicalId")
                        .IsUnique();

                    b.HasIndex("TechnicalId")
                        .IsUnique();

                    b.ToTable("FieldStats");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Goalkeeping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AerialReach")
                        .HasColumnType("integer");

                    b.Property<int>("CommandOfArea")
                        .HasColumnType("integer");

                    b.Property<int>("Communication")
                        .HasColumnType("integer");

                    b.Property<int>("Eccentricity")
                        .HasColumnType("integer");

                    b.Property<int>("FirstTouch")
                        .HasColumnType("integer");

                    b.Property<int>("Handling")
                        .HasColumnType("integer");

                    b.Property<int>("Kicking")
                        .HasColumnType("integer");

                    b.Property<int>("OneOnOnes")
                        .HasColumnType("integer");

                    b.Property<int>("Passing")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Punching")
                        .HasColumnType("integer");

                    b.Property<int>("Reflexes")
                        .HasColumnType("integer");

                    b.Property<int>("RushingOut")
                        .HasColumnType("integer");

                    b.Property<int>("Throwing")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Goalkeeping");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("League");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Mental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("Aggression")
                        .HasColumnType("integer");

                    b.Property<int>("Anticipation")
                        .HasColumnType("integer");

                    b.Property<int>("Bravery")
                        .HasColumnType("integer");

                    b.Property<int>("Composure")
                        .HasColumnType("integer");

                    b.Property<int>("Concentration")
                        .HasColumnType("integer");

                    b.Property<int>("Decisions")
                        .HasColumnType("integer");

                    b.Property<int>("Determination")
                        .HasColumnType("integer");

                    b.Property<int>("Flair")
                        .HasColumnType("integer");

                    b.Property<int>("Leadership")
                        .HasColumnType("integer");

                    b.Property<int>("OffTheBall")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Positioning")
                        .HasColumnType("integer");

                    b.Property<int>("Teamwork")
                        .HasColumnType("integer");

                    b.Property<int>("Vision")
                        .HasColumnType("integer");

                    b.Property<int>("WorkRate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Mental");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Physical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("Acceleration")
                        .HasColumnType("integer");

                    b.Property<int>("Agility")
                        .HasColumnType("integer");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<int>("JumpingReach")
                        .HasColumnType("integer");

                    b.Property<int>("NaturalFitness")
                        .HasColumnType("integer");

                    b.Property<int>("Pace")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Physical");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Contract")
                        .HasColumnType("date");

                    b.Property<int>("CurrentAbility")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEuCitizen")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGoalKeeper")
                        .HasColumnType("boolean");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("League_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PotentialAbility")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string[]>("Role")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Team_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Wage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("League_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Training_Facilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Youth_Facilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Technical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("Corners")
                        .HasColumnType("integer");

                    b.Property<int>("Crossing")
                        .HasColumnType("integer");

                    b.Property<int>("Dribbling")
                        .HasColumnType("integer");

                    b.Property<int>("Finishing")
                        .HasColumnType("integer");

                    b.Property<int>("FirstTouch")
                        .HasColumnType("integer");

                    b.Property<int>("FreeKickTaking")
                        .HasColumnType("integer");

                    b.Property<int>("Heading")
                        .HasColumnType("integer");

                    b.Property<int>("LongShots")
                        .HasColumnType("integer");

                    b.Property<int>("LongThrows")
                        .HasColumnType("integer");

                    b.Property<int>("Marking")
                        .HasColumnType("integer");

                    b.Property<int>("Passing")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyTaking")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Tackling")
                        .HasColumnType("integer");

                    b.Property<int>("Technique")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Technical");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.FieldStats", b =>
                {
                    b.HasOne("FootballScout.Data.Entities.Mental", "Mental")
                        .WithOne("FieldStats")
                        .HasForeignKey("FootballScout.Data.Entities.FieldStats", "MentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballScout.Data.Entities.Physical", "Physical")
                        .WithOne("FieldStats")
                        .HasForeignKey("FootballScout.Data.Entities.FieldStats", "PhysicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballScout.Data.Entities.Technical", "Technical")
                        .WithOne("FieldStats")
                        .HasForeignKey("FootballScout.Data.Entities.FieldStats", "TechnicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mental");

                    b.Navigation("Physical");

                    b.Navigation("Technical");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Goalkeeping", b =>
                {
                    b.HasOne("FootballScout.Data.Entities.Player", "Player")
                        .WithOne("Goalkeeping")
                        .HasForeignKey("FootballScout.Data.Entities.Goalkeeping", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Mental", b =>
                {
                    b.HasOne("FootballScout.Data.Entities.Player", "Player")
                        .WithOne("Mental")
                        .HasForeignKey("FootballScout.Data.Entities.Mental", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Physical", b =>
                {
                    b.HasOne("FootballScout.Data.Entities.Player", "Player")
                        .WithOne("Physical")
                        .HasForeignKey("FootballScout.Data.Entities.Physical", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Player", b =>
                {
                    b.HasOne("FootballScout.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Team", b =>
                {
                    b.HasOne("FootballScout.Data.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Technical", b =>
                {
                    b.HasOne("FootballScout.Data.Entities.Player", "Player")
                        .WithOne("Technical")
                        .HasForeignKey("FootballScout.Data.Entities.Technical", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Mental", b =>
                {
                    b.Navigation("FieldStats")
                        .IsRequired();
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Physical", b =>
                {
                    b.Navigation("FieldStats")
                        .IsRequired();
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Player", b =>
                {
                    b.Navigation("Goalkeeping")
                        .IsRequired();

                    b.Navigation("Mental")
                        .IsRequired();

                    b.Navigation("Physical")
                        .IsRequired();

                    b.Navigation("Technical")
                        .IsRequired();
                });

            modelBuilder.Entity("FootballScout.Data.Entities.Technical", b =>
                {
                    b.Navigation("FieldStats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
